// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACIrTMMpME_UemMaZQ-PzntSHfWXKuQdE',
    appId: '1:152257043206:web:be344224cbc3b8988d1c87',
    messagingSenderId: '152257043206',
    projectId: 'fir-flutter-codelab-f23e3',
    authDomain: 'fir-flutter-codelab-f23e3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f23e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBle4fHpwY3aDQn4PCYVlwQqUhHuvAOo',
    appId: '1:152257043206:android:c884fab4525454978d1c87',
    messagingSenderId: '152257043206',
    projectId: 'fir-flutter-codelab-f23e3',
    storageBucket: 'fir-flutter-codelab-f23e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMMOLHli3Cp3aaon6AKQeahXbhnAGIZM',
    appId: '1:152257043206:ios:3981eede798d252b8d1c87',
    messagingSenderId: '152257043206',
    projectId: 'fir-flutter-codelab-f23e3',
    storageBucket: 'fir-flutter-codelab-f23e3.firebasestorage.app',
    iosClientId: '152257043206-lhuir904ra8346rb903btg5mgenpk1qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMMOLHli3Cp3aaon6AKQeahXbhnAGIZM',
    appId: '1:152257043206:ios:3981eede798d252b8d1c87',
    messagingSenderId: '152257043206',
    projectId: 'fir-flutter-codelab-f23e3',
    storageBucket: 'fir-flutter-codelab-f23e3.firebasestorage.app',
    iosClientId: '152257043206-lhuir904ra8346rb903btg5mgenpk1qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
